# Generated by Django 4.2.6 on 2024-01-22 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.order'),
        ),
    ]
